name: Hola Mundo

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Hola mundo!!!"
        
      - name: Touch file  # Crea el archivo
        run: |
          touch hola.txt
          ls -al
          
      - name: Set text  # Agrega texto al archivo
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al
          
      - name: Read file  # Lee el archivo
        run: |
          cat hola.txt
          ls -al

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        
      - name: Directorio
        run: ls -al

      - name: Instalar
        run: |
          cd .github/workflows
          ls -al
